/*
 * Copyright (C) 2013 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.michael.feng.tools;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

public class SQLiteHelper extends SQLiteOpenHelper {

	private static final int DB_VERSION = 6;
	private static final String DB_NAME = "bossweather.db";
	public static final String TB_NAME = "cities";
	public static final String COL_ID = "_id";
	public static final String COL_NAME = "name";
	public static final String COL_PROVINCE = "province";
	public static final String COL_CODE = "code";
	public static final String COL_STATUS = "status";
	public static final String COL_UPDATED = "updated";

	// DB creation SQL for table cities
	private static final String DB_CREATE_SQL = 
			  "CREATE TABLE cities"
			+ "(_id INTEGER PRIMARY KEY AUTOINCREMENT, "
			+ "name VARCHAR NOT NULL,"
			+ "province VARCHAR NOT NULL,"
			+ "code VARCHAR NOT NULL,"
			+ "status CHAR(1) DEFAULT 0 NOT NULL," 
			+ "updated DATE DEFAULT CURRENT_DATE NOT NULL)";
	
	private static final String INSERT_SQL1 =  "INSERT INTO cities values(1, 'Beijing' ,    'Beijing' ,    'BJ',  0, DATETIME('now'))";
	private static final String INSERT_SQL2 =  "INSERT INTO cities values(2, 'Shanghai',    'Shanghai',    'SH',  0, DATETIME('now'))";
	private static final String INSERT_SQL3 =  "INSERT INTO cities values(3, 'Tianjing',    'Tianjing',    'TJ',  0, DATETIME('now'))";
	private static final String INSERT_SQL4 =  "INSERT INTO cities values(4, 'Chongqin',    'Chongqin',    'CQ',  0, DATETIME('now'))";
	private static final String INSERT_SQL5 =  "INSERT INTO cities values(5, 'Haerbin',     'Heilongjiang','HEB', 0, DATETIME('now'))";
	private static final String INSERT_SQL6 =  "INSERT INTO cities values(6, 'Qiqihaer',    'Heilongjiang','QQHE',0, DATETIME('now'))";
	private static final String INSERT_SQL7 =  "INSERT INTO cities values(7, 'Jixi',        'Heilongjiang','JX',  0, DATETIME('now'))";
	private static final String INSERT_SQL8 =  "INSERT INTO cities values(8, 'Shuangyashan','Heilongjiang','SYS', 0, DATETIME('now'))";
	private static final String INSERT_SQL9 =  "INSERT INTO cities values(9, 'Daqin',       'Heilongjiang','DQ',  0, DATETIME('now'))";
	private static final String INSERT_SQL10 = "INSERT INTO cities values(10,'Jiamusi',     'Heilongjiang','JMS', 0, DATETIME('now'))";
	private static final String INSERT_SQL11 = "INSERT INTO cities values(11,'Qitaihe',     'Heilongjiang','QTH', 0, DATETIME('now'))";
	private static final String INSERT_SQL12 = "INSERT INTO cities values(12,'Mudanjiang',  'Heilongjiang','MDJ', 0, DATETIME('now'))";
	private static final String INSERT_SQL13 = "INSERT INTO cities values(13,'Heihe',       'Heilongjiang','HH',  0, DATETIME('now'))";
	private static final String INSERT_SQL14 = "INSERT INTO cities values(14,'Suihua',      'Heilongjiang','SH',  0, DATETIME('now'))";
	private static final String INSERT_SQL15 = "INSERT INTO cities values(15,'Daxinganling','Heilongjiang','DXAL',0, DATETIME('now'))";
	private static final String INSERT_SQL16 = "INSERT INTO cities values(16,'Changchun',   'Jilin','CC',0, DATETIME('now'))";
	private static final String INSERT_SQL17 = "INSERT INTO cities values(17,'Jilin',       'Jilin','JL',0, DATETIME('now'))";
	private static final String INSERT_SQL18 = "INSERT INTO cities values(18,'Siping',      'Jilin','SP',0, DATETIME('now'))";
	private static final String INSERT_SQL19 = "INSERT INTO cities values(19,'Liangyuan',   'Jilin','LY',0, DATETIME('now'))";
	private static final String INSERT_SQL20 = "INSERT INTO cities values(20,'Tonghua',     'Jilin','TH',0, DATETIME('now'))";
	private static final String INSERT_SQL21 = "INSERT INTO cities values(21,'Baishan',     'Jilin','BS',0, DATETIME('now'))";
	private static final String INSERT_SQL22 = "INSERT INTO cities values(22,'Songyuan',    'Jilin','SY',0, DATETIME('now'))";
	private static final String INSERT_SQL23 = "INSERT INTO cities values(23,'Baicheng',    'Jilin','BC',0, DATETIME('now'))";
	private static final String INSERT_SQL24 = "INSERT INTO cities values(24,'Yanbian',     'Jilin','YB',0, DATETIME('now'))";
	private static final String INSERT_SQL25 = "INSERT INTO cities values(25,'Shenyang',    'Liangning','SY',0, DATETIME('now'))";
	private static final String INSERT_SQL26 = "INSERT INTO cities values(26,'Daliang',     'Liangning','DL',0, DATETIME('now'))";
	private static final String INSERT_SQL27 = "INSERT INTO cities values(27,'Anshan',      'Liangning','AS',0, DATETIME('now'))";
	private static final String INSERT_SQL28 = "INSERT INTO cities values(28,'Fushun',      'Liangning','FS',0, DATETIME('now'))";
	private static final String INSERT_SQL29 = "INSERT INTO cities values(29,'Benxi',       'Liangning','BX',0, DATETIME('now'))";
	private static final String INSERT_SQL30 = "INSERT INTO cities values(30,'Dandong',     'Liangning','DD',0, DATETIME('now'))";
	private static final String INSERT_SQL31 = "INSERT INTO cities values(31,'Jingzhou',    'Liangning','JZ',0, DATETIME('now'))";
	private static final String INSERT_SQL32 = "INSERT INTO cities values(32,'Yinkou',      'Liangning','YK',0, DATETIME('now'))";
	private static final String INSERT_SQL33 = "INSERT INTO cities values(33,'Fuxin',       'Liangning','FX',0, DATETIME('now'))";
	private static final String INSERT_SQL34 = "INSERT INTO cities values(34,'Liangyang',   'Liangning','LY',0, DATETIME('now'))";
	private static final String INSERT_SQL35 = "INSERT INTO cities values(35,'Panjin',      'Liangning','PJ',0, DATETIME('now'))";
	private static final String INSERT_SQL36 = "INSERT INTO cities values(36,'Chaoyang',    'Liangning','CY',0, DATETIME('now'))";
	private static final String INSERT_SQL37 = "INSERT INTO cities values(37,'Huludao',     'Liangning','HLD',0, DATETIME('now'))";
	private static final String INSERT_SQL38 = "INSERT INTO cities values(38,'Jinan',       'Shandong','JN',0, DATETIME('now'))";
	private static final String INSERT_SQL39 = "INSERT INTO cities values(39,'Qindao',      'Shandong','QD',0, DATETIME('now'))";
	private static final String INSERT_SQL40 = "INSERT INTO cities values(40,'Zibo',        'Shandong','ZB',0, DATETIME('now'))";
	private static final String INSERT_SQL41 = "INSERT INTO cities values(41,'Zaozhuang',   'Shandong','ZZ',0, DATETIME('now'))";
	private static final String INSERT_SQL42 = "INSERT INTO cities values(42,'Dongyin',     'Shandong','DY',0, DATETIME('now'))";
	private static final String INSERT_SQL43 = "INSERT INTO cities values(43,'Yantai',      'Shandong','YT',0, DATETIME('now'))";
	private static final String INSERT_SQL44 = "INSERT INTO cities values(44,'Zhifang',     'Shandong','ZF',0, DATETIME('now'))";
	private static final String INSERT_SQL45 = "INSERT INTO cities values(45,'Jining',      'Shandong','JN',0, DATETIME('now'))";
	private static final String INSERT_SQL46 = "INSERT INTO cities values(46,'Taian',       'Shandong','TA',0, DATETIME('now'))";
	private static final String INSERT_SQL47 = "INSERT INTO cities values(47,'Weihai',      'Shandong','WH',0, DATETIME('now'))";
	private static final String INSERT_SQL48 = "INSERT INTO cities values(48,'Rizhao',      'Shandong','RZ',0, DATETIME('now'))";
	private static final String INSERT_SQL49 = "INSERT INTO cities values(49,'Laiwu',       'Shandong','LW',0, DATETIME('now'))";
	private static final String INSERT_SQL50 = "INSERT INTO cities values(50,'Linyi',       'Shandong','LY',0, DATETIME('now'))";
	private static final String INSERT_SQL51 = "INSERT INTO cities values(51,'Dezhou',      'Shandong','DZ',0, DATETIME('now'))";
	private static final String INSERT_SQL52 = "INSERT INTO cities values(52,'Liaocheng',   'Shandong','LC',0, DATETIME('now'))";
	private static final String INSERT_SQL53 = "INSERT INTO cities values(53,'Binzhou',     'Shandong','BZ',0, DATETIME('now'))";
	private static final String INSERT_SQL54 = "INSERT INTO cities values(54,'Heze',        'Shandong','HZ',0, DATETIME('now'))";
	private static final String INSERT_SQL55 = "INSERT INTO cities values(55,'Taiyuan',     'Shanxi','TY',0, DATETIME('now'))";
	private static final String INSERT_SQL56 = "INSERT INTO cities values(56,'Datong',      'Shanxi','DT',0, DATETIME('now'))";
	private static final String INSERT_SQL57 = "INSERT INTO cities values(57,'Yangquan',    'Shanxi','YQ',0, DATETIME('now'))";
	private static final String INSERT_SQL58 = "INSERT INTO cities values(58,'Changzhi',    'Shanxi','CZ',0, DATETIME('now'))";
	private static final String INSERT_SQL59 = "INSERT INTO cities values(59,'Jincheng',    'Shanxi','JC',0, DATETIME('now'))";
	private static final String INSERT_SQL60 = "INSERT INTO cities values(60,'Shuozhou',    'Shanxi','SZ',0, DATETIME('now'))";
	private static final String INSERT_SQL61 = "INSERT INTO cities values(61,'JinZhong',    'Shanxi','JZ',0, DATETIME('now'))";
	private static final String INSERT_SQL62 = "INSERT INTO cities values(62,'Yuncheng',    'Shanxi','YC',0, DATETIME('now'))";
	private static final String INSERT_SQL63 = "INSERT INTO cities values(63,'Xinzhou',     'Shanxi','XZ',0, DATETIME('now'))";
	private static final String INSERT_SQL64 = "INSERT INTO cities values(64,'Linfen',      'Shanxi','LF',0, DATETIME('now'))";
	private static final String INSERT_SQL65 = "INSERT INTO cities values(65,'Lvliang',     'Shanxi','LL',0, DATETIME('now'))";
	private static final String INSERT_SQL66 = "INSERT INTO cities values(66,'Shijiazhuang','Hebei','SJZ',0, DATETIME('now'))";
	private static final String INSERT_SQL67 = "INSERT INTO cities values(67,'Tangshan',    'Hebei','TS',0, DATETIME('now'))";
	private static final String INSERT_SQL68 = "INSERT INTO cities values(68,'Qinhuangdao', 'Hebei','QHD',0, DATETIME('now'))";
	private static final String INSERT_SQL69 = "INSERT INTO cities values(69,'Handan',      'Hebei','HD',0, DATETIME('now'))";
	private static final String INSERT_SQL70 = "INSERT INTO cities values(70,'Xingtai',     'Hebei','XT',0, DATETIME('now'))";
	private static final String INSERT_SQL71 = "INSERT INTO cities values(71,'Handan',      'Hebei','HD',0, DATETIME('now'))";
	private static final String INSERT_SQL72 = "INSERT INTO cities values(72,'Baoding',     'Hebei','BD',0, DATETIME('now'))";
	private static final String INSERT_SQL73 = "INSERT INTO cities values(73,'Zhangjiakou', 'Hebei','ZJK',0, DATETIME('now'))";
	private static final String INSERT_SQL74 = "INSERT INTO cities values(74,'Chende',      'Hebei','CD',0, DATETIME('now'))";
	private static final String INSERT_SQL75 = "INSERT INTO cities values(75,'Cangzhou',    'Hebei','CZ',0, DATETIME('now'))";
	private static final String INSERT_SQL76 = "INSERT INTO cities values(76,'Langfang',    'Hebei','LF',0, DATETIME('now'))";
	private static final String INSERT_SQL77 = "INSERT INTO cities values(77,'Hengshui',    'Hebei','HS',0, DATETIME('now'))";
	private static final String INSERT_SQL78 = "INSERT INTO cities values(78,'Handan',      'Hebei','HD',0, DATETIME('now'))";
	private static final String INSERT_SQL79 = "INSERT INTO cities values(79,'Handan',      'Hebei','HD',0, DATETIME('now'))";
	private static final String INSERT_SQL80 = "INSERT INTO cities values(80,'Zhengzhou',   'Henan','ZZ',0, DATETIME('now'))";
	private static final String INSERT_SQL81 = "INSERT INTO cities values(81,'Kaifeng',     'Henan','KF',0, DATETIME('now'))";
	private static final String INSERT_SQL82 = "INSERT INTO cities values(82,'Luoyang',     'Henan','LY',0, DATETIME('now'))";
	private static final String INSERT_SQL83 = "INSERT INTO cities values(83,'Pingdingshan','Henan','PDS',0, DATETIME('now'))";
	private static final String INSERT_SQL84 = "INSERT INTO cities values(84,'Anyang',      'Henan','AY',0, DATETIME('now'))";
	private static final String INSERT_SQL85 = "INSERT INTO cities values(85,'Hebi',        'Henan','HB',0, DATETIME('now'))";
	private static final String INSERT_SQL86 = "INSERT INTO cities values(86,'Xinxiang',    'Henan','XY',0, DATETIME('now'))";
	private static final String INSERT_SQL87 = "INSERT INTO cities values(87,'Jiaozuo',     'Henan','JZ',0, DATETIME('now'))";
	private static final String INSERT_SQL88 = "INSERT INTO cities values(88,'Jiyuan',      'Henan','JY',0, DATETIME('now'))";
	private static final String INSERT_SQL89 = "INSERT INTO cities values(89,'Puyang',      'Henan','PY',0, DATETIME('now'))";
	private static final String INSERT_SQL90 = "INSERT INTO cities values(90,'Xuchang',     'Henan','XC',0, DATETIME('now'))";
	private static final String INSERT_SQL91 = "INSERT INTO cities values(91,'LuoHe',       'Henan','LH',0, DATETIME('now'))";
	private static final String INSERT_SQL92 = "INSERT INTO cities values(92,'Sanmengxia',  'Henan','SMX',0, DATETIME('now'))";
	private static final String INSERT_SQL93 = "INSERT INTO cities values(93,'Nanyang',     'Henan','NY',0, DATETIME('now'))";
	private static final String INSERT_SQL94 = "INSERT INTO cities values(94,'Shangqiu',    'Henan','SQ',0, DATETIME('now'))";
	private static final String INSERT_SQL95 = "INSERT INTO cities values(95,'Xinyang',     'Henan','XY',0, DATETIME('now'))";
	private static final String INSERT_SQL96 = "INSERT INTO cities values(96,'Zhoukou',     'Henan','ZK',0, DATETIME('now'))";
	private static final String INSERT_SQL97 = "INSERT INTO cities values(97,'Zhumadian',   'Henan','ZMD',0, DATETIME('now'))";
	private static final String INSERT_SQL98 = "INSERT INTO cities values(98,'Wuhan',       'Hubei','WH',0, DATETIME('now'))";
	private static final String INSERT_SQL99 = "INSERT INTO cities values(99,'Huangshi',    'Hubei','HS',0, DATETIME('now'))";
	private static final String INSERT_SQL100= "INSERT INTO cities values(100,'Shiyan',     'Hubei','SY',0, DATETIME('now'))";
	private static final String INSERT_SQL101= "INSERT INTO cities values(101,'Yichang',    'Hubei','YC',0, DATETIME('now'))";
	private static final String INSERT_SQL102= "INSERT INTO cities values(102,'Ezhou',      'Hubei','EZ',0, DATETIME('now'))";
	private static final String INSERT_SQL103= "INSERT INTO cities values(103,'Jingmen',    'Hubei','JM',0, DATETIME('now'))";
	private static final String INSERT_SQL104= "INSERT INTO cities values(104,'Xiaogan',    'Hubei','XG',0, DATETIME('now'))";
	private static final String INSERT_SQL105= "INSERT INTO cities values(105,'Jingzhou',   'Hubei','JZ',0, DATETIME('now'))";
	private static final String INSERT_SQL106= "INSERT INTO cities values(106,'Huanggang',  'Hubei','HG',0, DATETIME('now'))";
	private static final String INSERT_SQL107= "INSERT INTO cities values(107,'Xianning',   'Hubei','XN',0, DATETIME('now'))";
	private static final String INSERT_SQL108= "INSERT INTO cities values(108,'Suizhou',    'Hubei','SZ',0, DATETIME('now'))";
	private static final String INSERT_SQL109= "INSERT INTO cities values(109,'Enshi',      'Hubei','ES',0, DATETIME('now'))";
	private static final String INSERT_SQL110= "INSERT INTO cities values(110,'Xiantao',    'Hubei','XT',0, DATETIME('now'))";
	private static final String INSERT_SQL111= "INSERT INTO cities values(111,'Qianjiang',  'Hubei','QJ',0, DATETIME('now'))";
	private static final String INSERT_SQL112= "INSERT INTO cities values(112,'Tianmeng',   'Hubei','TM',0, DATETIME('now'))";
	private static final String INSERT_SQL113= "INSERT INTO cities values(113,'Shennongjia','Hubei','SNJ',0, DATETIME('now'))";
	private static final String INSERT_SQL114= "INSERT INTO cities values(114,'Changsha',   'Hunan','CS',0, DATETIME('now'))";
	private static final String INSERT_SQL115= "INSERT INTO cities values(115,'Zhuzhou',    'Hunan','ZZ',0, DATETIME('now'))";
	private static final String INSERT_SQL116= "INSERT INTO cities values(116,'Xiangtan',   'Hunan','XT',0, DATETIME('now'))";
	private static final String INSERT_SQL117= "INSERT INTO cities values(117,'Hengyang',   'Hunan','HY',0, DATETIME('now'))";
	private static final String INSERT_SQL118= "INSERT INTO cities values(118,'Shaoyang',   'Hunan','SY',0, DATETIME('now'))";
	private static final String INSERT_SQL119= "INSERT INTO cities values(119,'Yueyang',    'Hunan','YY',0, DATETIME('now'))";
	private static final String INSERT_SQL120= "INSERT INTO cities values(120,'Changde',    'Hunan','CD',0, DATETIME('now'))";
	private static final String INSERT_SQL121= "INSERT INTO cities values(121,'Zhangjiajie','Hunan','ZJJ',0, DATETIME('now'))";
	private static final String INSERT_SQL122= "INSERT INTO cities values(122,'Yiyang',     'Hunan','YY',0, DATETIME('now'))";
	private static final String INSERT_SQL123= "INSERT INTO cities values(123,'Chenzhou',   'Hunan','CZ',0, DATETIME('now'))";
	private static final String INSERT_SQL124= "INSERT INTO cities values(124,'Yongzhou',   'Hunan','YZ',0, DATETIME('now'))";
	private static final String INSERT_SQL125= "INSERT INTO cities values(125,'Huaihua',    'Hunan','HH',0, DATETIME('now'))";
	private static final String INSERT_SQL126= "INSERT INTO cities values(126,'Loudi',      'Hunan','LD',0, DATETIME('now'))";
	private static final String INSERT_SQL127= "INSERT INTO cities values(127,'Xiangxi',    'Hunan','XX',0, DATETIME('now'))";
	private static final String INSERT_SQL128= "INSERT INTO cities values(128,'Haikou',     'Hainan','HK',0, DATETIME('now'))";
	private static final String INSERT_SQL129= "INSERT INTO cities values(129,'Sanya',      'Hainan','SY',0, DATETIME('now'))";
	private static final String INSERT_SQL130= "INSERT INTO cities values(130,'Wuzhishan',  'Hainan','WZS',0, DATETIME('now'))";
	private static final String INSERT_SQL131= "INSERT INTO cities values(131,'Qionghai',   'Hainan','QH',0, DATETIME('now'))";
	private static final String INSERT_SQL132= "INSERT INTO cities values(132,'Danzhou',    'Hainan','DZ',0, DATETIME('now'))";
	private static final String INSERT_SQL133= "INSERT INTO cities values(133,'Wenchang',   'Hainan','WC',0, DATETIME('now'))";
	private static final String INSERT_SQL134= "INSERT INTO cities values(134,'Wanning',    'Hainan','WN',0, DATETIME('now'))";
	private static final String INSERT_SQL135= "INSERT INTO cities values(135,'Dongfang',   'Hainan','DF',0, DATETIME('now'))";
	private static final String INSERT_SQL136= "INSERT INTO cities values(136,'Anding',     'Hainan','AD',0, DATETIME('now'))";
	private static final String INSERT_SQL137= "INSERT INTO cities values(137,'Tunchang',   'Hainan','TC',0, DATETIME('now'))";
	private static final String INSERT_SQL138= "INSERT INTO cities values(138,'Chengmai',   'Hainan','CM',0, DATETIME('now'))";
	private static final String INSERT_SQL139= "INSERT INTO cities values(139,'Lingao',     'Hainan','LG',0, DATETIME('now'))";
	private static final String INSERT_SQL140= "INSERT INTO cities values(140,'Chengmai',   'Hainan','CM',0, DATETIME('now'))";
	private static final String INSERT_SQL141= "INSERT INTO cities values(141,'Baisha',     'Hainan','BS',0, DATETIME('now'))";
	private static final String INSERT_SQL142= "INSERT INTO cities values(142,'Changjiang', 'Hainan','CJ',0, DATETIME('now'))";
	private static final String INSERT_SQL143= "INSERT INTO cities values(143,'Ledong',     'Hainan','LD',0, DATETIME('now'))";
	private static final String INSERT_SQL144= "INSERT INTO cities values(144,'Lingshui',   'Hainan','LS',0, DATETIME('now'))";
	private static final String INSERT_SQL145= "INSERT INTO cities values(145,'Baoting',    'Hainan','BT',0, DATETIME('now'))";
	private static final String INSERT_SQL146= "INSERT INTO cities values(146,'Qiongzhong', 'Hainan','QZ',0, DATETIME('now'))";
	private static final String INSERT_SQL147= "INSERT INTO cities values(147,'Nanjing',    'Jiangsu','NJ',0, DATETIME('now'))";
	private static final String INSERT_SQL148= "INSERT INTO cities values(148,'Wuxi',       'Jiangsu','WX',0, DATETIME('now'))";
	private static final String INSERT_SQL149= "INSERT INTO cities values(149,'Xuzhou',     'Jiangsu','XZ',0, DATETIME('now'))";
	private static final String INSERT_SQL150= "INSERT INTO cities values(150,'Changzhou',  'Jiangsu','CZ',0, DATETIME('now'))";
	private static final String INSERT_SQL151= "INSERT INTO cities values(151,'Suzhou',     'Jiangsu','SZ',0, DATETIME('now'))";
	private static final String INSERT_SQL152= "INSERT INTO cities values(152,'Nantong',    'Jiangsu','NT',0, DATETIME('now'))";
	private static final String INSERT_SQL153= "INSERT INTO cities values(153,'Lianyungang','Jiangsu','LYG',0, DATETIME('now'))";
	private static final String INSERT_SQL154= "INSERT INTO cities values(154,'Huaian',     'Jiangsu','HA',0, DATETIME('now'))";
	private static final String INSERT_SQL155= "INSERT INTO cities values(155,'Yancheng',   'Jiangsu','YC',0, DATETIME('now'))";
	private static final String INSERT_SQL156= "INSERT INTO cities values(156,'Yangzhou',   'Jiangsu','YZ',0, DATETIME('now'))";
	private static final String INSERT_SQL157= "INSERT INTO cities values(157,'Zhenjiang',  'Jiangsu','ZJ',0, DATETIME('now'))";
	private static final String INSERT_SQL158= "INSERT INTO cities values(158,'Taizhou',    'Jiangsu','TZ',0, DATETIME('now'))";
	private static final String INSERT_SQL159= "INSERT INTO cities values(159,'Suqian',     'Jiangsu','SQ',0, DATETIME('now'))";
	private static final String INSERT_SQL160= "INSERT INTO cities values(160,'Nanchang',   'Jiangxi','NC',0, DATETIME('now'))";
	private static final String INSERT_SQL161= "INSERT INTO cities values(161,'Jingdezhen', 'Jiangxi','JDZ',0, DATETIME('now'))";
	private static final String INSERT_SQL162= "INSERT INTO cities values(162,'Pingxiang',  'Jiangxi','PX',0, DATETIME('now'))";
	private static final String INSERT_SQL163= "INSERT INTO cities values(163,'Jiujiang',   'Jiangxi','JJ',0, DATETIME('now'))";
	private static final String INSERT_SQL164= "INSERT INTO cities values(164,'Xinyu',      'Jiangxi','XY',0, DATETIME('now'))";
	private static final String INSERT_SQL165= "INSERT INTO cities values(165,'Yintan',     'Jiangxi','YT',0, DATETIME('now'))";
	private static final String INSERT_SQL166= "INSERT INTO cities values(166,'Ganzhou',    'Jiangxi','GZ',0, DATETIME('now'))";
	private static final String INSERT_SQL167= "INSERT INTO cities values(167,'Jian',       'Jiangxi','JA',0, DATETIME('now'))";
	private static final String INSERT_SQL168= "INSERT INTO cities values(168,'Yichun',     'Jiangxi','YC',0, DATETIME('now'))";
	private static final String INSERT_SQL169= "INSERT INTO cities values(169,'Fuzhou',     'Jiangxi','FZ',0, DATETIME('now'))";
	private static final String INSERT_SQL170= "INSERT INTO cities values(170,'Shangrao',   'Jiangxi','SR',0, DATETIME('now'))";
	private static final String INSERT_SQL171= "INSERT INTO cities values(171,'Guangzhou',  'Guangdong','GZ',0, DATETIME('now'))";
	private static final String INSERT_SQL172= "INSERT INTO cities values(172,'Shaoguan',   'Guangdong','SG',0, DATETIME('now'))";
	private static final String INSERT_SQL173= "INSERT INTO cities values(173,'Shenzheng',  'Guangdong','SZ',0, DATETIME('now'))";
	private static final String INSERT_SQL174= "INSERT INTO cities values(174,'Zhuhai',     'Guangdong','ZH',0, DATETIME('now'))";
	private static final String INSERT_SQL175= "INSERT INTO cities values(175,'Shantou',    'Guangdong','ST',0, DATETIME('now'))";
	private static final String INSERT_SQL176= "INSERT INTO cities values(176,'Foshan',     'Guangdong','FS',0, DATETIME('now'))";
	private static final String INSERT_SQL177= "INSERT INTO cities values(177,'Jiangmen',   'Guangdong','JM',0, DATETIME('now'))";
	private static final String INSERT_SQL178= "INSERT INTO cities values(178,'Zhanjiang',  'Guangdong','ZJ',0, DATETIME('now'))";
	private static final String INSERT_SQL179= "INSERT INTO cities values(179,'Maoming',    'Guangdong','MM',0, DATETIME('now'))";
	private static final String INSERT_SQL180= "INSERT INTO cities values(180,'Zhaoqin',    'Guangdong','ZQ',0, DATETIME('now'))";
	private static final String INSERT_SQL181= "INSERT INTO cities values(181,'Huizhou',    'Guangdong','HZ',0, DATETIME('now'))";
	private static final String INSERT_SQL182= "INSERT INTO cities values(182,'Meizhou',    'Guangdong','MZ',0, DATETIME('now'))";
	private static final String INSERT_SQL183= "INSERT INTO cities values(183,'Shanwei',    'Guangdong','SW',0, DATETIME('now'))";
	private static final String INSERT_SQL184= "INSERT INTO cities values(184,'Heyuan',     'Guangdong','HT',0, DATETIME('now'))";
	private static final String INSERT_SQL185= "INSERT INTO cities values(185,'Yangjiang',  'Guangdong','YJ',0, DATETIME('now'))";
	private static final String INSERT_SQL186= "INSERT INTO cities values(186,'Qingyuan',   'Guangdong','QY',0, DATETIME('now'))";
	private static final String INSERT_SQL187= "INSERT INTO cities values(187,'Dongwan',    'Guangdong','DW',0, DATETIME('now'))";
	private static final String INSERT_SQL188= "INSERT INTO cities values(188,'Zhongshan',  'Guangdong','ZS',0, DATETIME('now'))";
	private static final String INSERT_SQL189= "INSERT INTO cities values(189,'Chaozhou',   'Guangdong','CZ',0, DATETIME('now'))";
	private static final String INSERT_SQL190= "INSERT INTO cities values(190,'Jieyang',    'Guangdong','JY',0, DATETIME('now'))";
	private static final String INSERT_SQL191= "INSERT INTO cities values(191,'Yunfu',      'Guangdong','YF',0, DATETIME('now'))";
	private static final String INSERT_SQL192= "INSERT INTO cities values(192,'Nanning',    'Guangxi','NN',0, DATETIME('now'))";
	private static final String INSERT_SQL193= "INSERT INTO cities values(193,'Liuzhou',    'Guangxi','LZ',0, DATETIME('now'))";
	private static final String INSERT_SQL194= "INSERT INTO cities values(194,'Guilin',     'Guangxi','GL',0, DATETIME('now'))";
	private static final String INSERT_SQL195= "INSERT INTO cities values(195,'Wuzhou',     'Guangxi','WZ',0, DATETIME('now'))";
	private static final String INSERT_SQL196= "INSERT INTO cities values(196,'Beihai',     'Guangxi','BH',0, DATETIME('now'))";
	private static final String INSERT_SQL197= "INSERT INTO cities values(197,'Fangchengang','Guangxi','FCG',0, DATETIME('now'))";
	private static final String INSERT_SQL198= "INSERT INTO cities values(198,'Qinzhou',    'Guangxi','QZ',0, DATETIME('now'))";
	private static final String INSERT_SQL199= "INSERT INTO cities values(199,'Guigang',    'Guangxi','GG',0, DATETIME('now'))";
	private static final String INSERT_SQL200= "INSERT INTO cities values(200,'Yulin',      'Guangxi','YL',0, DATETIME('now'))";
	private static final String INSERT_SQL201= "INSERT INTO cities values(201,'Baise',      'Guangxi','BS',0, DATETIME('now'))";
	private static final String INSERT_SQL202= "INSERT INTO cities values(202,'Hezhou',     'Guangxi','HZ',0, DATETIME('now'))";
	private static final String INSERT_SQL203= "INSERT INTO cities values(203,'Hechi',      'Guangxi','HC',0, DATETIME('now'))";
	private static final String INSERT_SQL204= "INSERT INTO cities values(204,'Laibin',     'Guangxi','LB',0, DATETIME('now'))";
	private static final String INSERT_SQL205= "INSERT INTO cities values(205,'Chongzuo',   'Guangxi','CZ',0, DATETIME('now'))";
	private static final String INSERT_SQL206= "INSERT INTO cities values(206,'Kunming',    'Yunnan','KM',0, DATETIME('now'))";
	private static final String INSERT_SQL207= "INSERT INTO cities values(207,'Qujing',     'Yunnan','QJ',0, DATETIME('now'))";
	private static final String INSERT_SQL208= "INSERT INTO cities values(208,'Yuxi',       'Yunnan','YX',0, DATETIME('now'))";
	private static final String INSERT_SQL209= "INSERT INTO cities values(209,'Baoshan',    'Yunnan','BS',0, DATETIME('now'))";
	private static final String INSERT_SQL210= "INSERT INTO cities values(210,'Zhaotong',   'Yunnan','ZT',0, DATETIME('now'))";
	private static final String INSERT_SQL211= "INSERT INTO cities values(211,'Lijiang',    'Yunnan','LJ',0, DATETIME('now'))";
	private static final String INSERT_SQL212= "INSERT INTO cities values(212,'Simao',      'Yunnan','SM',0, DATETIME('now'))";
	private static final String INSERT_SQL213= "INSERT INTO cities values(213,'Lincang',    'Yunnan','LC',0, DATETIME('now'))";
	private static final String INSERT_SQL214= "INSERT INTO cities values(214,'Chuxiong',   'Yunnan','CX',0, DATETIME('now'))";
	private static final String INSERT_SQL215= "INSERT INTO cities values(215,'Honghe',     'Yunnan','HH',0, DATETIME('now'))";
	private static final String INSERT_SQL216= "INSERT INTO cities values(216,'Wenshan',    'Yunnan','WS',0, DATETIME('now'))";
	private static final String INSERT_SQL217= "INSERT INTO cities values(217,'Xishuangbanna','Yunnan','XSBN',0, DATETIME('now'))";
	private static final String INSERT_SQL218= "INSERT INTO cities values(218,'Dali',       'Yunnan','DL',0, DATETIME('now'))";
	private static final String INSERT_SQL219= "INSERT INTO cities values(219,'Dehong',     'Yunnan','DH',0, DATETIME('now'))";
	private static final String INSERT_SQL220= "INSERT INTO cities values(220,'Nujiang',    'Yunnan','NJ',0, DATETIME('now'))";
	private static final String INSERT_SQL221= "INSERT INTO cities values(221,'Diqin',      'Yunnan','DQ',0, DATETIME('now'))";
	private static final String INSERT_SQL222= "INSERT INTO cities values(222,'Guiyang',    'Guizhou','GY',0, DATETIME('now'))";
	private static final String INSERT_SQL223= "INSERT INTO cities values(223,'Liupanshui', 'Guizhou','LPS',0, DATETIME('now'))";
	private static final String INSERT_SQL224= "INSERT INTO cities values(224,'Zunyi',      'Guizhou','ZY',0, DATETIME('now'))";
	private static final String INSERT_SQL225= "INSERT INTO cities values(225,'Anshun',     'Guizhou','AS',0, DATETIME('now'))";
	private static final String INSERT_SQL226= "INSERT INTO cities values(226,'Tongren',    'Guizhou','TR',0, DATETIME('now'))";
	private static final String INSERT_SQL227= "INSERT INTO cities values(227,'Qianxinan',  'Guizhou','QXN',0, DATETIME('now'))";
	private static final String INSERT_SQL228= "INSERT INTO cities values(228,'Qiandongnan','Guizhou','QDN',0, DATETIME('now'))";
	private static final String INSERT_SQL229= "INSERT INTO cities values(229,'Qiannan',    'Guizhou','QN',0, DATETIME('now'))";
	private static final String INSERT_SQL230= "INSERT INTO cities values(230,'Bijie',      'Guizhou','BJ',0, DATETIME('now'))";
	private static final String INSERT_SQL231= "INSERT INTO cities values(231,'Chengdu',    'Sichuan','CD',0, DATETIME('now'))";
	private static final String INSERT_SQL232= "INSERT INTO cities values(232,'Zigong',     'Sichuan','ZG',0, DATETIME('now'))";
	private static final String INSERT_SQL233= "INSERT INTO cities values(233,'Panzhihua',  'Sichuan','GZH',0, DATETIME('now'))";
	private static final String INSERT_SQL234= "INSERT INTO cities values(234,'Luzhou',     'Sichuan','LZ',0, DATETIME('now'))";
	private static final String INSERT_SQL235= "INSERT INTO cities values(235,'Deyang',     'Sichuan','DY',0, DATETIME('now'))";
	private static final String INSERT_SQL236= "INSERT INTO cities values(236,'Mianyang',   'Sichuan','MY',0, DATETIME('now'))";
	private static final String INSERT_SQL237= "INSERT INTO cities values(237,'Guangyuan',  'Sichuan','GY',0, DATETIME('now'))";
	private static final String INSERT_SQL238= "INSERT INTO cities values(238,'Suining',    'Sichuan','SN',0, DATETIME('now'))";
	private static final String INSERT_SQL239= "INSERT INTO cities values(239,'Neijiang',   'Sichuan','NJ',0, DATETIME('now'))";
	private static final String INSERT_SQL240= "INSERT INTO cities values(240,'Leshan',     'Sichuan','LS',0, DATETIME('now'))";
	private static final String INSERT_SQL241= "INSERT INTO cities values(241,'Nanchong',   'Sichuan','NC',0, DATETIME('now'))";
	private static final String INSERT_SQL242= "INSERT INTO cities values(242,'Meishan',    'Sichuan','MS',0, DATETIME('now'))";
	private static final String INSERT_SQL243= "INSERT INTO cities values(243,'Yibin',      'Sichuan','YB',0, DATETIME('now'))";
	private static final String INSERT_SQL244= "INSERT INTO cities values(244,'Guangan',    'Sichuan','GG',0, DATETIME('now'))";
	private static final String INSERT_SQL245= "INSERT INTO cities values(245,'Dazhou',     'Sichuan','DZ',0, DATETIME('now'))";
	private static final String INSERT_SQL246= "INSERT INTO cities values(246,'Yaan',       'Sichuan','YA',0, DATETIME('now'))";
	private static final String INSERT_SQL247= "INSERT INTO cities values(247,'Bazhong',    'Sichuan','BZ',0, DATETIME('now'))";
	private static final String INSERT_SQL248= "INSERT INTO cities values(248,'Ziyang',     'Sichuan','ZY',0, DATETIME('now'))";
	private static final String INSERT_SQL249= "INSERT INTO cities values(249,'Aba',        'Sichuan','AB',0, DATETIME('now'))";
	private static final String INSERT_SQL250= "INSERT INTO cities values(250,'Ganmu',      'Sichuan','GM',0, DATETIME('now'))";
	private static final String INSERT_SQL251= "INSERT INTO cities values(251,'Liangshan',  'Sichuan','LS',0, DATETIME('now'))";
	private static final String INSERT_SQL252= "INSERT INTO cities values(252,'Huhehaote',  'Neimenggu','HHHT',0, DATETIME('now'))";
	private static final String INSERT_SQL253= "INSERT INTO cities values(253,'Baotou',     'Neimenggu','BT',0, DATETIME('now'))";
	private static final String INSERT_SQL254= "INSERT INTO cities values(254,'Wuhai',      'Neimenggu','WH',0, DATETIME('now'))";
	private static final String INSERT_SQL255= "INSERT INTO cities values(255,'Chifeng',    'Neimenggu','CF',0, DATETIME('now'))";
	private static final String INSERT_SQL256= "INSERT INTO cities values(256,'Tongliao',   'Neimenggu','TL',0, DATETIME('now'))";
	private static final String INSERT_SQL257= "INSERT INTO cities values(257,'Eerduosi',   'Neimenggu','EEDS',0, DATETIME('now'))";
	private static final String INSERT_SQL258= "INSERT INTO cities values(258,'Hulunbeier', 'Neimenggu','HLBE',0, DATETIME('now'))";
	private static final String INSERT_SQL259= "INSERT INTO cities values(259,'Bayannaoer', 'Neimenggu','BYNE',0, DATETIME('now'))";
	private static final String INSERT_SQL260= "INSERT INTO cities values(260,'Wulanchabu', 'Neimenggu','WLCB',0, DATETIME('now'))";
	private static final String INSERT_SQL261= "INSERT INTO cities values(261,'Xinganmeng', 'Neimenggu','XAM',0, DATETIME('now'))";
	private static final String INSERT_SQL262= "INSERT INTO cities values(262,'Xilinguolemeng',  'Neimenggu','XLGLM',0, DATETIME('now'))";
	private static final String INSERT_SQL263= "INSERT INTO cities values(263,'Alashanmeng','Neimenggu','ALSM',0, DATETIME('now'))";
	private static final String INSERT_SQL264= "INSERT INTO cities values(264,'Yinchuan',   'Ningxia','YC',0, DATETIME('now'))";
	private static final String INSERT_SQL265= "INSERT INTO cities values(265,'Shizuishan', 'Ningxia','SZS',0, DATETIME('now'))";
	private static final String INSERT_SQL266= "INSERT INTO cities values(266,'Wuzhong',    'Ningxia','WZ',0, DATETIME('now'))";
	private static final String INSERT_SQL267= "INSERT INTO cities values(267,'Guyuan',     'Ningxia','GY',0, DATETIME('now'))";
	private static final String INSERT_SQL268= "INSERT INTO cities values(268,'Zhongwei',   'Ningxia','ZW',0, DATETIME('now'))";
	private static final String INSERT_SQL269= "INSERT INTO cities values(269,'Lanzhou',    'Gansu','LZ',0, DATETIME('now'))";
	private static final String INSERT_SQL270= "INSERT INTO cities values(270,'Jiayuguan',  'Gansu','JYG',0, DATETIME('now'))";
	private static final String INSERT_SQL271= "INSERT INTO cities values(271,'Jinchang',   'Gansu','JC',0, DATETIME('now'))";
	private static final String INSERT_SQL272= "INSERT INTO cities values(272,'Baiyin',     'Gansu','BY',0, DATETIME('now'))";
	private static final String INSERT_SQL273= "INSERT INTO cities values(273,'Tianshui',   'Gansu','TS',0, DATETIME('now'))";
	private static final String INSERT_SQL274= "INSERT INTO cities values(274,'Weiwu',      'Gansu','WW',0, DATETIME('now'))";
	private static final String INSERT_SQL275= "INSERT INTO cities values(275,'Zhangye',    'Gansu','ZY',0, DATETIME('now'))";
	private static final String INSERT_SQL276= "INSERT INTO cities values(276,'Pingliang',  'Gansu','PL',0, DATETIME('now'))";
	private static final String INSERT_SQL277= "INSERT INTO cities values(277,'Jiuquan',    'Gansu','JQ',0, DATETIME('now'))";
	private static final String INSERT_SQL278= "INSERT INTO cities values(278,'Qinyang',    'Gansu','QY',0, DATETIME('now'))";
	private static final String INSERT_SQL279= "INSERT INTO cities values(279,'Dingxi',     'Gansu','DX',0, DATETIME('now'))";
	private static final String INSERT_SQL280= "INSERT INTO cities values(280,'Longnan',    'Gansu','LN',0, DATETIME('now'))";
	private static final String INSERT_SQL281= "INSERT INTO cities values(281,'Linxia',     'Gansu','LX',0, DATETIME('now'))";
	private static final String INSERT_SQL282= "INSERT INTO cities values(282,'Gannan',     'Gansu','GN',0, DATETIME('now'))";
	private static final String INSERT_SQL283= "INSERT INTO cities values(283,'Xinning',    'Qinghai','XN',0, DATETIME('now'))";
	private static final String INSERT_SQL284= "INSERT INTO cities values(284,'Haidong',    'Qinghai','HD',0, DATETIME('now'))";
	private static final String INSERT_SQL285= "INSERT INTO cities values(285,'Haibei',     'Qinghai','HB',0, DATETIME('now'))";
	private static final String INSERT_SQL286= "INSERT INTO cities values(286,'Huangnan',   'Qinghai','HN',0, DATETIME('now'))";
	private static final String INSERT_SQL287= "INSERT INTO cities values(287,'Hainan',     'Qinghai','HN',0, DATETIME('now'))";
	private static final String INSERT_SQL288= "INSERT INTO cities values(288,'Guoluo',     'Qinghai','GL',0, DATETIME('now'))";
	private static final String INSERT_SQL289= "INSERT INTO cities values(289,'Yushu',      'Qinghai','YS',0, DATETIME('now'))";
	private static final String INSERT_SQL290= "INSERT INTO cities values(290,'Haixi',      'Qinghai','HX',0, DATETIME('now'))";
	private static final String INSERT_SQL292= "INSERT INTO cities values(292,'Lasha',      'Xizang','LS',0, DATETIME('now'))";
	private static final String INSERT_SQL293= "INSERT INTO cities values(293,'Changdu',    'Xizang','CD',0, DATETIME('now'))";
	private static final String INSERT_SQL294= "INSERT INTO cities values(294,'Shannan',    'Xizang','SN',0, DATETIME('now'))";
	private static final String INSERT_SQL295= "INSERT INTO cities values(295,'Rikaze',     'Xizang','RKZ',0, DATETIME('now'))";
	private static final String INSERT_SQL296= "INSERT INTO cities values(296,'Naqu',       'Xizang','NQ',0, DATETIME('now'))";
	private static final String INSERT_SQL297= "INSERT INTO cities values(297,'Ali',        'Xizang','AL',0, DATETIME('now'))";
	private static final String INSERT_SQL298= "INSERT INTO cities values(298,'Linzhi',     'Xizang','LZ',0, DATETIME('now'))";
	private static final String INSERT_SQL299= "INSERT INTO cities values(299,'Wulumuqi',   'Xinjiang','WLMQ',0, DATETIME('now'))";
	private static final String INSERT_SQL300= "INSERT INTO cities values(300,'Kelayima',   'Xinjiang','KLYM',0, DATETIME('now'))";
	private static final String INSERT_SQL301= "INSERT INTO cities values(301,'Tulufan',    'Xinjiang','TUF',0, DATETIME('now'))";
	private static final String INSERT_SQL302= "INSERT INTO cities values(302,'Hami',       'Xinjiang','HM',0, DATETIME('now'))";
	private static final String INSERT_SQL303= "INSERT INTO cities values(303,'Changji',    'Xinjiang','CJ',0, DATETIME('now'))";
	private static final String INSERT_SQL304= "INSERT INTO cities values(304,'Boertala',   'Xinjiang','BETLM',0, DATETIME('now'))";
	private static final String INSERT_SQL305= "INSERT INTO cities values(305,'Bayinguoleng',   'Xinjiang','BYGL',0, DATETIME('now'))";
	private static final String INSERT_SQL306= "INSERT INTO cities values(306,'Akesu',     'Xinjiang','AKS',0, DATETIME('now'))";
	private static final String INSERT_SQL307= "INSERT INTO cities values(307,'Kezilesukeerkezi',   'Xinjiang','KZLSKEKZ',0, DATETIME('now'))";
	private static final String INSERT_SQL308= "INSERT INTO cities values(308,'Kashi',     'Xinjiang','KS',0, DATETIME('now'))";
	private static final String INSERT_SQL309= "INSERT INTO cities values(309,'Hetian',    'Xinjiang','HT',0, DATETIME('now'))";
	private static final String INSERT_SQL310= "INSERT INTO cities values(310,'Yili',      'Xinjiang','YL',0, DATETIME('now'))";
	private static final String INSERT_SQL311= "INSERT INTO cities values(311,'Tacheng',   'Xinjiang','TC',0, DATETIME('now'))";
	private static final String INSERT_SQL312= "INSERT INTO cities values(312,'Aletai',    'Xinjiang','ALT',0, DATETIME('now'))";
	private static final String INSERT_SQL313= "INSERT INTO cities values(313,'Shihezi',   'Xinjiang','SHZ',0, DATETIME('now'))";
	private static final String INSERT_SQL314= "INSERT INTO cities values(314,'Alaer',     'Xinjiang','ALE',0, DATETIME('now'))";
	private static final String INSERT_SQL315= "INSERT INTO cities values(315,'Tumushuke', 'Xinjiang','TMSK',0, DATETIME('now'))";
	private static final String INSERT_SQL316= "INSERT INTO cities values(316,'Wujiaqu',   'Xinjiang','WJQ',0, DATETIME('now'))";
	private static final String INSERT_SQL317= "INSERT INTO cities values(317,'Hefei',     'Anhui','HF',0, DATETIME('now'))";
	private static final String INSERT_SQL318= "INSERT INTO cities values(318,'Wuhu',      'Anhui','WH',0, DATETIME('now'))";
	private static final String INSERT_SQL319= "INSERT INTO cities values(319,'Bengbu',    'Anhui','BB',0, DATETIME('now'))";
	private static final String INSERT_SQL320= "INSERT INTO cities values(320,'Haian',     'Anhui','HA',0, DATETIME('now'))";
	private static final String INSERT_SQL321= "INSERT INTO cities values(321,'Maanshan',  'Anhui','MAS',0, DATETIME('now'))";
	private static final String INSERT_SQL322= "INSERT INTO cities values(322,'Huaibei',   'Anhui','HB',0, DATETIME('now'))";
	private static final String INSERT_SQL323= "INSERT INTO cities values(323,'Tongling',  'Anhui','TL',0, DATETIME('now'))";
	private static final String INSERT_SQL324= "INSERT INTO cities values(324,'Anqin',     'Anhui','AQ',0, DATETIME('now'))";
	private static final String INSERT_SQL325= "INSERT INTO cities values(325,'Huangshan', 'Anhui','HS',0, DATETIME('now'))";
	private static final String INSERT_SQL326= "INSERT INTO cities values(326,'Chuzhou',   'Anhui','CZ',0, DATETIME('now'))";
	private static final String INSERT_SQL327= "INSERT INTO cities values(327,'Fuyang',    'Anhui','FY',0, DATETIME('now'))";
	private static final String INSERT_SQL328= "INSERT INTO cities values(328,'Suzhou',    'Anhui','SZ',0, DATETIME('now'))";
	private static final String INSERT_SQL329= "INSERT INTO cities values(329,'Chaohu',    'Anhui','CH',0, DATETIME('now'))";
	private static final String INSERT_SQL330= "INSERT INTO cities values(330,'Liuan',     'Anhui','LA',0, DATETIME('now'))";
	private static final String INSERT_SQL331= "INSERT INTO cities values(331,'Haozhou',   'Anhui','HZ',0, DATETIME('now'))";
	private static final String INSERT_SQL332= "INSERT INTO cities values(332,'Chizhou',   'Anhui','CZ',0, DATETIME('now'))";
	private static final String INSERT_SQL333= "INSERT INTO cities values(333,'Xuancheng', 'Anhui','XC',0, DATETIME('now'))";
	private static final String INSERT_SQL334= "INSERT INTO cities values(334,'Hangzhou',  'Zhejiang','HZ',0, DATETIME('now'))";
	private static final String INSERT_SQL335= "INSERT INTO cities values(335,'Ningbo',    'Zhejiang','NB',0, DATETIME('now'))";
	private static final String INSERT_SQL336= "INSERT INTO cities values(336,'Wenzhou',   'Zhejiang','WZ',0, DATETIME('now'))";
	private static final String INSERT_SQL337= "INSERT INTO cities values(337,'Jiaxing',   'Zhejiang','JX',0, DATETIME('now'))";
	private static final String INSERT_SQL338= "INSERT INTO cities values(338,'Huzhou',    'Zhejiang','HZ',0, DATETIME('now'))";
	private static final String INSERT_SQL339= "INSERT INTO cities values(339,'Shaoxing',  'Zhejiang','SX',0, DATETIME('now'))";
	private static final String INSERT_SQL340= "INSERT INTO cities values(340,'Jinhua',    'Zhejiang','JH',0, DATETIME('now'))";
	private static final String INSERT_SQL341= "INSERT INTO cities values(341,'Quzhou',    'Zhejiang','QZ',0, DATETIME('now'))";
	private static final String INSERT_SQL342= "INSERT INTO cities values(342,'Zhoushan',  'Zhejiang','ZS',0, DATETIME('now'))";
	private static final String INSERT_SQL343= "INSERT INTO cities values(343,'Taizhou',   'Zhejiang','TZ',0, DATETIME('now'))";
	private static final String INSERT_SQL344= "INSERT INTO cities values(344,'Lishui',    'Zhejiang','LS',0, DATETIME('now'))";
	private static final String INSERT_SQL345= "INSERT INTO cities values(345,'Fuzhou',    'Fujian','FZ',0, DATETIME('now'))";
	private static final String INSERT_SQL346= "INSERT INTO cities values(346,'Xiameng',   'Fujian','XM',0, DATETIME('now'))";
	private static final String INSERT_SQL347= "INSERT INTO cities values(347,'Putian',    'Fujian','PT',0, DATETIME('now'))";
	private static final String INSERT_SQL348= "INSERT INTO cities values(348,'Sanming',   'Fujian','SM',0, DATETIME('now'))";
	private static final String INSERT_SQL349= "INSERT INTO cities values(349,'Quanzhou',  'Fujian','QZ',0, DATETIME('now'))";
	private static final String INSERT_SQL350= "INSERT INTO cities values(350,'Zhangzhou', 'Fujian','ZZ',0, DATETIME('now'))";
	private static final String INSERT_SQL351= "INSERT INTO cities values(351,'Nanping',   'Fujian','NP',0, DATETIME('now'))";
	private static final String INSERT_SQL352= "INSERT INTO cities values(352,'Longyan',   'Fujian','LY',0, DATETIME('now'))";
	private static final String INSERT_SQL353= "INSERT INTO cities values(353,'Ningde',    'Fujian','ND',0, DATETIME('now'))";
	private static final String INSERT_SQL354= "INSERT INTO cities values(354,'Xianggang', 'Xianggang','XG',0, DATETIME('now'))";
	private static final String INSERT_SQL355= "INSERT INTO cities values(355,'Taiwan',    'Taiwan','TW',0, DATETIME('now'))";
	private static final String INSERT_SQL356= "INSERT INTO cities values(356,'Aomeng',    'Aomeng','AM',0, DATETIME('now'))";
	
	public SQLiteHelper(Context context) {
		super(context, DB_NAME, null, DB_VERSION);
	}

	@Override
	public void onCreate(SQLiteDatabase database) {
		database.execSQL(DB_CREATE_SQL);
		database.execSQL(INSERT_SQL1);
		database.execSQL(INSERT_SQL2);
		database.execSQL(INSERT_SQL3);
		database.execSQL(INSERT_SQL4);
		database.execSQL(INSERT_SQL5);
		database.execSQL(INSERT_SQL6);
		database.execSQL(INSERT_SQL7);
		database.execSQL(INSERT_SQL8);
		database.execSQL(INSERT_SQL9);
		database.execSQL(INSERT_SQL10);
		database.execSQL(INSERT_SQL11);
		database.execSQL(INSERT_SQL12);
		database.execSQL(INSERT_SQL13);
		database.execSQL(INSERT_SQL14);
		database.execSQL(INSERT_SQL15);
		database.execSQL(INSERT_SQL16);
		database.execSQL(INSERT_SQL17);
		database.execSQL(INSERT_SQL18);
		database.execSQL(INSERT_SQL19);
		database.execSQL(INSERT_SQL20);
		database.execSQL(INSERT_SQL21);
		database.execSQL(INSERT_SQL22);
		database.execSQL(INSERT_SQL23);
		database.execSQL(INSERT_SQL24);
		database.execSQL(INSERT_SQL25);
		database.execSQL(INSERT_SQL26);
		database.execSQL(INSERT_SQL27);
		database.execSQL(INSERT_SQL28);
		database.execSQL(INSERT_SQL29);
		database.execSQL(INSERT_SQL30);
		database.execSQL(INSERT_SQL31);
		database.execSQL(INSERT_SQL32);
		database.execSQL(INSERT_SQL33);
		database.execSQL(INSERT_SQL34);
		database.execSQL(INSERT_SQL35);
		database.execSQL(INSERT_SQL36);
		database.execSQL(INSERT_SQL37);
		database.execSQL(INSERT_SQL38);
		database.execSQL(INSERT_SQL39);
		database.execSQL(INSERT_SQL40);
		database.execSQL(INSERT_SQL41);
		database.execSQL(INSERT_SQL42);
		database.execSQL(INSERT_SQL43);
		database.execSQL(INSERT_SQL44);
		database.execSQL(INSERT_SQL45);
		database.execSQL(INSERT_SQL46);
		database.execSQL(INSERT_SQL47);
		database.execSQL(INSERT_SQL48);
		database.execSQL(INSERT_SQL49);
		database.execSQL(INSERT_SQL50);
		database.execSQL(INSERT_SQL51);
		database.execSQL(INSERT_SQL52);
		database.execSQL(INSERT_SQL53);
		database.execSQL(INSERT_SQL54);
		database.execSQL(INSERT_SQL55);
		database.execSQL(INSERT_SQL56);
		database.execSQL(INSERT_SQL57);
		database.execSQL(INSERT_SQL58);
		database.execSQL(INSERT_SQL59);
		database.execSQL(INSERT_SQL60);
		database.execSQL(INSERT_SQL61);
		database.execSQL(INSERT_SQL62);
		database.execSQL(INSERT_SQL63);
		database.execSQL(INSERT_SQL64);
		database.execSQL(INSERT_SQL65);
		database.execSQL(INSERT_SQL66);
		database.execSQL(INSERT_SQL67);
		database.execSQL(INSERT_SQL68);
		database.execSQL(INSERT_SQL69);
		database.execSQL(INSERT_SQL70);
		database.execSQL(INSERT_SQL71);
		database.execSQL(INSERT_SQL72);
		database.execSQL(INSERT_SQL73);
		database.execSQL(INSERT_SQL74);
		database.execSQL(INSERT_SQL75);
		database.execSQL(INSERT_SQL76);
		database.execSQL(INSERT_SQL77);
		database.execSQL(INSERT_SQL78);
		database.execSQL(INSERT_SQL79);
		database.execSQL(INSERT_SQL80);
		database.execSQL(INSERT_SQL81);
		database.execSQL(INSERT_SQL82);
		database.execSQL(INSERT_SQL83);
		database.execSQL(INSERT_SQL84);
		database.execSQL(INSERT_SQL85);
		database.execSQL(INSERT_SQL86);
		database.execSQL(INSERT_SQL87);
		database.execSQL(INSERT_SQL88);
		database.execSQL(INSERT_SQL89);
		database.execSQL(INSERT_SQL90);
		database.execSQL(INSERT_SQL91);
		database.execSQL(INSERT_SQL92);
		database.execSQL(INSERT_SQL93);
		database.execSQL(INSERT_SQL94);
		database.execSQL(INSERT_SQL95);
		database.execSQL(INSERT_SQL96);
		database.execSQL(INSERT_SQL97);
		database.execSQL(INSERT_SQL98);
		database.execSQL(INSERT_SQL99);
		database.execSQL(INSERT_SQL100);
		database.execSQL(INSERT_SQL101);
		database.execSQL(INSERT_SQL102);
		database.execSQL(INSERT_SQL103);
		database.execSQL(INSERT_SQL104);
		database.execSQL(INSERT_SQL105);
		database.execSQL(INSERT_SQL106);
		database.execSQL(INSERT_SQL107);
		database.execSQL(INSERT_SQL108);
		database.execSQL(INSERT_SQL109);
		database.execSQL(INSERT_SQL110);
		database.execSQL(INSERT_SQL111);
		database.execSQL(INSERT_SQL112);
		database.execSQL(INSERT_SQL113);
		database.execSQL(INSERT_SQL114);
		database.execSQL(INSERT_SQL115);
		database.execSQL(INSERT_SQL116);
		database.execSQL(INSERT_SQL117);
		database.execSQL(INSERT_SQL118);
		database.execSQL(INSERT_SQL119);
		database.execSQL(INSERT_SQL120);
		database.execSQL(INSERT_SQL121);
		database.execSQL(INSERT_SQL122);
		database.execSQL(INSERT_SQL123);
		database.execSQL(INSERT_SQL124);
		database.execSQL(INSERT_SQL125);
		database.execSQL(INSERT_SQL126);
		database.execSQL(INSERT_SQL127);
		database.execSQL(INSERT_SQL128);
		database.execSQL(INSERT_SQL129);
		database.execSQL(INSERT_SQL130);
		database.execSQL(INSERT_SQL131);
		database.execSQL(INSERT_SQL132);
		database.execSQL(INSERT_SQL133);
		database.execSQL(INSERT_SQL134);
		database.execSQL(INSERT_SQL135);
		database.execSQL(INSERT_SQL136);
		database.execSQL(INSERT_SQL137);
		database.execSQL(INSERT_SQL138);
		database.execSQL(INSERT_SQL139);
		database.execSQL(INSERT_SQL140);
		database.execSQL(INSERT_SQL141);
		database.execSQL(INSERT_SQL142);
		database.execSQL(INSERT_SQL143);
		database.execSQL(INSERT_SQL144);
		database.execSQL(INSERT_SQL145);
		database.execSQL(INSERT_SQL146);
		database.execSQL(INSERT_SQL147);
		database.execSQL(INSERT_SQL148);
		database.execSQL(INSERT_SQL149);
		database.execSQL(INSERT_SQL150);
		database.execSQL(INSERT_SQL151);
		database.execSQL(INSERT_SQL152);
		database.execSQL(INSERT_SQL153);
		database.execSQL(INSERT_SQL154);
		database.execSQL(INSERT_SQL155);
		database.execSQL(INSERT_SQL156);
		database.execSQL(INSERT_SQL157);
		database.execSQL(INSERT_SQL158);
		database.execSQL(INSERT_SQL159);
		database.execSQL(INSERT_SQL160);
		database.execSQL(INSERT_SQL161);
		database.execSQL(INSERT_SQL162);
		database.execSQL(INSERT_SQL163);
		database.execSQL(INSERT_SQL164);
		database.execSQL(INSERT_SQL165);
		database.execSQL(INSERT_SQL166);
		database.execSQL(INSERT_SQL167);
		database.execSQL(INSERT_SQL168);
		database.execSQL(INSERT_SQL169);
		database.execSQL(INSERT_SQL170);
		database.execSQL(INSERT_SQL171);
		database.execSQL(INSERT_SQL172);
		database.execSQL(INSERT_SQL173);
		database.execSQL(INSERT_SQL174);
		database.execSQL(INSERT_SQL175);
		database.execSQL(INSERT_SQL176);
		database.execSQL(INSERT_SQL177);
		database.execSQL(INSERT_SQL178);
		database.execSQL(INSERT_SQL179);
		database.execSQL(INSERT_SQL180);
		database.execSQL(INSERT_SQL181);
		database.execSQL(INSERT_SQL182);
		database.execSQL(INSERT_SQL183);
		database.execSQL(INSERT_SQL184);
		database.execSQL(INSERT_SQL185);
		database.execSQL(INSERT_SQL186);
		database.execSQL(INSERT_SQL187);
		database.execSQL(INSERT_SQL188);
		database.execSQL(INSERT_SQL189);
		database.execSQL(INSERT_SQL190);
		database.execSQL(INSERT_SQL191);
		database.execSQL(INSERT_SQL192);
		database.execSQL(INSERT_SQL193);
		database.execSQL(INSERT_SQL194);
		database.execSQL(INSERT_SQL195);
		database.execSQL(INSERT_SQL196);
		database.execSQL(INSERT_SQL197);
		database.execSQL(INSERT_SQL198);
		database.execSQL(INSERT_SQL199);
		database.execSQL(INSERT_SQL200);
		database.execSQL(INSERT_SQL201);
		database.execSQL(INSERT_SQL202);
		database.execSQL(INSERT_SQL203);
		database.execSQL(INSERT_SQL204);
		database.execSQL(INSERT_SQL205);
		database.execSQL(INSERT_SQL206);
		database.execSQL(INSERT_SQL207);
		database.execSQL(INSERT_SQL208);
		database.execSQL(INSERT_SQL209);
		database.execSQL(INSERT_SQL210);
		database.execSQL(INSERT_SQL211);
		database.execSQL(INSERT_SQL212);
		database.execSQL(INSERT_SQL213);
		database.execSQL(INSERT_SQL214);
		database.execSQL(INSERT_SQL215);
		database.execSQL(INSERT_SQL216);
		database.execSQL(INSERT_SQL217);
		database.execSQL(INSERT_SQL218);
		database.execSQL(INSERT_SQL219);
		database.execSQL(INSERT_SQL220);
		database.execSQL(INSERT_SQL221);
		database.execSQL(INSERT_SQL222);
		database.execSQL(INSERT_SQL223);
		database.execSQL(INSERT_SQL224);
		database.execSQL(INSERT_SQL225);
		database.execSQL(INSERT_SQL226);
		database.execSQL(INSERT_SQL227);
		database.execSQL(INSERT_SQL228);
		database.execSQL(INSERT_SQL229);
		database.execSQL(INSERT_SQL230);
		database.execSQL(INSERT_SQL231);
		database.execSQL(INSERT_SQL232);
		database.execSQL(INSERT_SQL233);
		database.execSQL(INSERT_SQL234);
		database.execSQL(INSERT_SQL235);
		database.execSQL(INSERT_SQL236);
		database.execSQL(INSERT_SQL237);
		database.execSQL(INSERT_SQL238);
		database.execSQL(INSERT_SQL239);
		database.execSQL(INSERT_SQL240);
		database.execSQL(INSERT_SQL241);
		database.execSQL(INSERT_SQL242);
		database.execSQL(INSERT_SQL243);
		database.execSQL(INSERT_SQL244);
		database.execSQL(INSERT_SQL245);
		database.execSQL(INSERT_SQL246);
		database.execSQL(INSERT_SQL247);
		database.execSQL(INSERT_SQL248);
		database.execSQL(INSERT_SQL249);
		database.execSQL(INSERT_SQL250);
		database.execSQL(INSERT_SQL251);
		database.execSQL(INSERT_SQL252);
		database.execSQL(INSERT_SQL253);
		database.execSQL(INSERT_SQL254);
		database.execSQL(INSERT_SQL255);
		database.execSQL(INSERT_SQL256);
		database.execSQL(INSERT_SQL257);
		database.execSQL(INSERT_SQL258);
		database.execSQL(INSERT_SQL259);
		database.execSQL(INSERT_SQL260);
		database.execSQL(INSERT_SQL261);
		database.execSQL(INSERT_SQL262);
		database.execSQL(INSERT_SQL263);
		database.execSQL(INSERT_SQL264);
		database.execSQL(INSERT_SQL265);
		database.execSQL(INSERT_SQL266);
		database.execSQL(INSERT_SQL267);
		database.execSQL(INSERT_SQL268);
		database.execSQL(INSERT_SQL269);
		database.execSQL(INSERT_SQL270);
		database.execSQL(INSERT_SQL271);
		database.execSQL(INSERT_SQL272);
		database.execSQL(INSERT_SQL273);
		database.execSQL(INSERT_SQL274);
		database.execSQL(INSERT_SQL275);
		database.execSQL(INSERT_SQL276);
		database.execSQL(INSERT_SQL277);
		database.execSQL(INSERT_SQL278);
		database.execSQL(INSERT_SQL279);
		database.execSQL(INSERT_SQL280);
		database.execSQL(INSERT_SQL281);
		database.execSQL(INSERT_SQL282);
		database.execSQL(INSERT_SQL283);
		database.execSQL(INSERT_SQL284);
		database.execSQL(INSERT_SQL285);
		database.execSQL(INSERT_SQL286);
		database.execSQL(INSERT_SQL287);
		database.execSQL(INSERT_SQL288);
		database.execSQL(INSERT_SQL289);
		database.execSQL(INSERT_SQL290);
		database.execSQL(INSERT_SQL292);
		database.execSQL(INSERT_SQL293);
		database.execSQL(INSERT_SQL294);
		database.execSQL(INSERT_SQL295);
		database.execSQL(INSERT_SQL296);
		database.execSQL(INSERT_SQL297);
		database.execSQL(INSERT_SQL298);
		database.execSQL(INSERT_SQL299);
		database.execSQL(INSERT_SQL300);
		database.execSQL(INSERT_SQL301);
		database.execSQL(INSERT_SQL302);
		database.execSQL(INSERT_SQL303);
		database.execSQL(INSERT_SQL304);
		database.execSQL(INSERT_SQL305);
		database.execSQL(INSERT_SQL306);
		database.execSQL(INSERT_SQL307);
		database.execSQL(INSERT_SQL308);
		database.execSQL(INSERT_SQL309);
		database.execSQL(INSERT_SQL310);
		database.execSQL(INSERT_SQL311);
		database.execSQL(INSERT_SQL312);
		database.execSQL(INSERT_SQL313);
		database.execSQL(INSERT_SQL314);
		database.execSQL(INSERT_SQL315);
		database.execSQL(INSERT_SQL316);
		database.execSQL(INSERT_SQL317);
		database.execSQL(INSERT_SQL318);
		database.execSQL(INSERT_SQL319);
		database.execSQL(INSERT_SQL320);
		database.execSQL(INSERT_SQL321);
		database.execSQL(INSERT_SQL322);
		database.execSQL(INSERT_SQL323);
		database.execSQL(INSERT_SQL324);
		database.execSQL(INSERT_SQL325);
		database.execSQL(INSERT_SQL326);
		database.execSQL(INSERT_SQL327);
		database.execSQL(INSERT_SQL328);
		database.execSQL(INSERT_SQL329);
		database.execSQL(INSERT_SQL330);
		database.execSQL(INSERT_SQL331);
		database.execSQL(INSERT_SQL332);
		database.execSQL(INSERT_SQL333);
		database.execSQL(INSERT_SQL334);
		database.execSQL(INSERT_SQL336);
		database.execSQL(INSERT_SQL337);
		database.execSQL(INSERT_SQL338);
		database.execSQL(INSERT_SQL339);
		database.execSQL(INSERT_SQL340);
		database.execSQL(INSERT_SQL341);
		database.execSQL(INSERT_SQL342);
		database.execSQL(INSERT_SQL343);
		database.execSQL(INSERT_SQL344);
		database.execSQL(INSERT_SQL345);
		database.execSQL(INSERT_SQL346);
		database.execSQL(INSERT_SQL347);
		database.execSQL(INSERT_SQL348);
		database.execSQL(INSERT_SQL349);
		database.execSQL(INSERT_SQL350);
		database.execSQL(INSERT_SQL351);
		database.execSQL(INSERT_SQL352);
		database.execSQL(INSERT_SQL353);
		database.execSQL(INSERT_SQL354);
		database.execSQL(INSERT_SQL355);
		database.execSQL(INSERT_SQL356);
	}

	@Override
	public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
		Log.w(SQLiteHelper.class.getName(), "Upgrading database from version "
				+ oldVersion + " to " + newVersion
				+ ", which will destroy all old data");
		db.execSQL("DROP TABLE IF EXISTS " + DB_NAME);
		onCreate(db);
	}
}
